---
title: "Einfluss von Frauen in Filmen"
description: |
  Mithilfe des Bechdel-Tests wird die Entwicklung der Frauenrolle in Filmen dargestellt.

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(tidyverse)
library(colorspace)
library(ggthemes)
```

````{r load_data}

# Filme von 1970 bis 2020, wenig Informationen pro Film
raw_bechdel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/raw_bechdel.csv')
# Filme von 1970 bis 2013, viele Informationen, viele Informationen pro Film

movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-09/movies.csv')
```

```{r}

raw_bechdel %>% 
  filter(year == 1970:2013) %>%
  ggplot() +
  aes(x = year, y =  as.numeric(rating), color = rating) +
  geom_point() +
  geom_jitter() +
  scale_color_continuous_sequential(palette = "Peach") +
  labs(x = "Jahr", y = "Bechdelwert") -> plot_1

movies %>% ggplot() +
  aes(x = year, y =  as.numeric(imdb_rating), group = year, color = imdb_rating) +
  geom_point() +
  geom_jitter() +
  scale_color_continuous_sequential(palette = "Mint") +
  labs(x = "Jahr", y = "IMDB Wert") -> plot_2

library(patchwork)

(plot_1 + plot_2) +
  plot_annotation(title = "Ab dem Jahr 1995 ist die Rolle von Frauen in Filmen präsenter", subtitle = "Vergleich von IMDB_Rating und Bechdel Test im Punktdiagramm")

```


